package tj.recipes;

import gregicadditions.item.metal.MetalCasing1;
import gregtech.api.items.metaitem.MetaItem;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraftforge.fluids.FluidRegistry;
import tj.blocks.BlockFusionCasings;
import tj.blocks.TJMetaBlocks;
import gregicadditions.GAValues;
import gregicadditions.item.CellCasing;
import gregicadditions.item.GAMetaBlocks;
import gregicadditions.item.GAMetaItems;
import gregicadditions.item.GAMultiblockCasing;
import gregicadditions.machines.GATileEntities;
import gregtech.api.unification.material.MarkerMaterials;
import gregtech.api.unification.ore.OrePrefix;
import gregtech.common.items.MetaItems;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

import java.util.ArrayList;
import java.util.List;

import static tj.items.TJMetaItems.*;
import static tj.items.TJMetaItems.FLUID_REGULATOR_MAX;
import static tj.machines.TJMetaTileEntities.*;
import static gregicadditions.GAMaterials.*;
import static gregicadditions.item.GAMetaItems.*;
import static gregicadditions.machines.GATileEntities.*;
import static gregicadditions.recipes.GARecipeMaps.ASSEMBLY_LINE_RECIPES;
import static gregtech.api.unification.material.MarkerMaterials.Tier.*;
import static gregtech.api.unification.material.Materials.*;
import static gregtech.common.items.MetaItems.*;
import static gregtech.common.metatileentities.MetaTileEntities.HULL;
import static tj.recipes.AssemblerRecipes.MATERIAL_TIER;

public class AssemblyLineRecipes {

    public static void init() {
        MetaItem<?>.MetaValueItem[] motors = {ELECTRIC_MOTOR_LV, ELECTRIC_MOTOR_MV, ELECTRIC_MOTOR_HV, ELECTRIC_MOTOR_EV, ELECTRIC_MOTOR_IV, ELECTRIC_MOTOR_LUV, ELECTRIC_MOTOR_ZPM, ELECTRIC_MOTOR_UV, ELECTRIC_MOTOR_UHV, ELECTRIC_MOTOR_UEV, ELECTRIC_MOTOR_UIV, ELECTRIC_MOTOR_UMV, ELECTRIC_MOTOR_UXV, ELECTRIC_MOTOR_MAX};
        MetaItem<?>.MetaValueItem[] emitters = {EMITTER_LV, EMITTER_MV, EMITTER_HV, EMITTER_EV, EMITTER_IV, EMITTER_LUV, EMITTER_ZPM, EMITTER_UV, EMITTER_UHV, EMITTER_UEV, EMITTER_UIV, EMITTER_UMV, EMITTER_UXV, EMITTER_MAX};
        MetaItem<?>.MetaValueItem[] sensors = {SENSOR_LV, SENSOR_MV, SENSOR_HV, SENSOR_EV, SENSOR_IV, SENSOR_LUV, SENSOR_ZPM, SENSOR_UV, SENSOR_UHV, SENSOR_UEV, SENSOR_UIV, SENSOR_UMV, SENSOR_UXV, SENSOR_MAX};
        MetaItem<?>.MetaValueItem[] pumps = {ELECTRIC_PUMP_LV, ELECTRIC_PUMP_MV, ELECTRIC_PUMP_HV, ELECTRIC_PUMP_EV, ELECTRIC_PUMP_IV, ELECTRIC_PUMP_LUV, ELECTRIC_PUMP_ZPM, ELECTRIC_PUMP_UV, ELECTRIC_PUMP_UHV, ELECTRIC_PUMP_UEV, ELECTRIC_PUMP_UIV, ELECTRIC_PUMP_UMV, ELECTRIC_PUMP_UXV, ELECTRIC_PUMP_MAX};
        MetaItem<?>.MetaValueItem[] conveyors = {CONVEYOR_MODULE_LV, CONVEYOR_MODULE_MV, CONVEYOR_MODULE_HV, CONVEYOR_MODULE_EV, CONVEYOR_MODULE_IV, CONVEYOR_MODULE_LUV, CONVEYOR_MODULE_ZPM, CONVEYOR_MODULE_UV, CONVEYOR_MODULE_UHV, CONVEYOR_MODULE_UEV, CONVEYOR_MODULE_UIV, CONVEYOR_MODULE_UMV, CONVEYOR_MODULE_UXV, CONVEYOR_MODULE_MAX};
        MetaItem<?>.MetaValueItem[] robotArms = {ROBOT_ARM_LV, ROBOT_ARM_MV, ROBOT_ARM_HV, ROBOT_ARM_EV, ROBOT_ARM_IV, ROBOT_ARM_LUV, ROBOT_ARM_ZPM, ROBOT_ARM_UV, ROBOT_ARM_UHV, ROBOT_ARM_UEV, ROBOT_ARM_UIV, ROBOT_ARM_UMV, ROBOT_ARM_UXV, ROBOT_ARM_MAX};
        MetaItem<?>.MetaValueItem[] regulators = {FLUID_REGULATOR_LV, FLUID_REGULATOR_MV, FLUID_REGULATOR_HV, FLUID_REGULATOR_EV, FLUID_REGULATOR_IV, FLUID_REGULATOR_LUV, FLUID_REGULATOR_ZPM, FLUID_REGULATOR_UV, FLUID_REGULATOR_UHV, null, null, FLUID_REGULATOR_UMV, null, FLUID_REGULATOR_MAX};

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(9216))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Polybenzimidazole.getFluid(4608))
                .fluidInputs(Naquadria.getFluid(2304))
                .inputs(LARGE_STEAM_TURBINE.getStackForm(12))
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(16))
                .inputs(ELECTRIC_PUMP_UV.getStackForm(16))
                .inputs(ROBOT_ARM_UV.getStackForm(12))
                .inputs(HIGH_POWER_INTEGRATED_CIRCUIT.getStackForm(64))
                .inputs(HIGH_POWER_INTEGRATED_CIRCUIT.getStackForm(64))
                .input(OrePrefix.wireGtSingle, UVSuperconductor, 64)
                .input(OrePrefix.pipeLarge, Steel, 64)
                .input(OrePrefix.plateDense, Steel, 7)
                .input(OrePrefix.gear, Steel, 16)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Superconductor)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Superconductor)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Superconductor)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Superconductor)
                .outputs(XL_STEAM_TURBINE.getStackForm())
                .EUt(491520)
                .duration(2400)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(9216))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Polybenzimidazole.getFluid(4608))
                .fluidInputs(Naquadria.getFluid(2304))
                .inputs(LARGE_GAS_TURBINE.getStackForm(12))
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(16))
                .inputs(ELECTRIC_PUMP_UV.getStackForm(16))
                .inputs(ROBOT_ARM_UV.getStackForm(12))
                .inputs(HIGH_POWER_INTEGRATED_CIRCUIT.getStackForm(64))
                .inputs(HIGH_POWER_INTEGRATED_CIRCUIT.getStackForm(64))
                .input(OrePrefix.wireGtSingle, UVSuperconductor, 64)
                .input(OrePrefix.pipeLarge, StainlessSteel, 64)
                .input(OrePrefix.plateDense, StainlessSteel, 7)
                .input(OrePrefix.gear, StainlessSteel, 16)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Superconductor)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Superconductor)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Superconductor)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Superconductor)
                .outputs(XL_GAS_TURBINE.getStackForm())
                .EUt(491520)
                .duration(2400)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(9216))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Polybenzimidazole.getFluid(4608))
                .fluidInputs(Bohrium.getFluid(2304))
                .inputs(HOT_COOLANT_TURBINE.getStackForm(12))
                .inputs(ELECTRIC_MOTOR_UHV.getStackForm(12))
                .inputs(ELECTRIC_PUMP_UHV.getStackForm(12))
                .inputs(ROBOT_ARM_UHV.getStackForm(12))
                .inputs(UHPIC.getStackForm(64))
                .inputs(UHPIC.getStackForm(64))
                .input(OrePrefix.wireGtSingle, UHVSuperconductor, 64)
                .input(OrePrefix.pipeLarge, Ultimet, 64)
                .input(OrePrefix.plateDense, Stellite, 7)
                .input(OrePrefix.gear, Stellite, 16)
                .input(OrePrefix.circuit, UEV)
                .input(OrePrefix.circuit, UEV)
                .input(OrePrefix.circuit, UEV)
                .input(OrePrefix.circuit, UEV)
                .outputs(XL_COOLANT_TURBINE.getStackForm())
                .EUt(1966080)
                .duration(2400)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(9216))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Polybenzimidazole.getFluid(4608))
                .fluidInputs(Seaborgium.getFluid(2304))
                .inputs(LARGE_PLASMA_TURBINE.getStackForm(12))
                .inputs(ELECTRIC_MOTOR_UHV.getStackForm(12))
                .inputs(ELECTRIC_PUMP_UHV.getStackForm(12))
                .inputs(ROBOT_ARM_UHV.getStackForm(12))
                .inputs(UHPIC.getStackForm(64))
                .inputs(UHPIC.getStackForm(64))
                .input(OrePrefix.wireGtSingle, UHVSuperconductor, 64)
                .input(OrePrefix.pipeLarge, TungstenSteel, 64)
                .input(OrePrefix.plateDense, TungstenSteel, 7)
                .input(OrePrefix.gear, TungstenSteel, 16)
                .input(OrePrefix.circuit, UEV)
                .input(OrePrefix.circuit, UEV)
                .input(OrePrefix.circuit, UEV)
                .input(OrePrefix.circuit, UEV)
                .outputs(XL_PLASMA_TURBINE.getStackForm())
                .EUt(1966080)
                .duration(2400)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(5760))
                .fluidInputs(Lubricant.getFluid(16000))
                .fluidInputs(Uranium238Isotope.getMaterial().getFluid(1440))
                .fluidInputs(Plutonium244Isotope.getMaterial().getFluid(1440))
                .inputs(MetaItems.HIGH_POWER_INTEGRATED_CIRCUIT.getStackForm(64))
                .input(OrePrefix.wireGtQuadruple, LuVSuperconductor, 64)
                .input(OrePrefix.plateDense, Einsteinium.getMaterial(), 4)
                .input(OrePrefix.plateDense, Rutherfordium, 4)
                .inputs(MetaItems.FIELD_GENERATOR_LUV.getStackForm(16))
                .inputs(MetaItems.EMITTER_LUV.getStackForm(16))
                .inputs(MetaItems.SENSOR_LUV.getStackForm(16))
                .inputs(GATileEntities.FUSION_REACTOR[0].getStackForm())
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Ultimate)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Ultimate)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Ultimate)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Ultimate)
                .outputs(INDUSTRIAL_FUSION_REACTOR_LUV.getStackForm())
                .EUt(60000)
                .duration(1000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(5760))
                .fluidInputs(Lubricant.getFluid(16000))
                .fluidInputs(Polonium.getFluid(2880))
                .fluidInputs(Lutetium.getFluid(2880))
                .inputs(MetaItems.HIGH_POWER_INTEGRATED_CIRCUIT.getStackForm(48))
                .inputs(MetaItems.HIGH_POWER_INTEGRATED_CIRCUIT.getStackForm(48))
                .input(OrePrefix.wireGtOctal, ZPMSuperconductor, 64)
                .input(OrePrefix.plateDense, Fermium.getMaterial(), 4)
                .input(OrePrefix.plateDense, Dubnium, 4)
                .inputs(MetaItems.FIELD_GENERATOR_ZPM.getStackForm(16))
                .inputs(MetaItems.EMITTER_ZPM.getStackForm(16))
                .inputs(MetaItems.SENSOR_ZPM.getStackForm(16))
                .inputs(GATileEntities.FUSION_REACTOR[1].getStackForm())
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Superconductor, 4)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Superconductor, 4)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Superconductor, 4)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Superconductor, 4)
                .outputs(INDUSTRIAL_FUSION_REACTOR_ZPM.getStackForm())
                .EUt(120000)
                .duration(1000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(5760))
                .fluidInputs(Lubricant.getFluid(16000))
                .fluidInputs(Copernicium.getFluid(5760))
                .fluidInputs(Meitnerium.getFluid(5760))
                .inputs(GAMetaItems.UHPIC.getStackForm(64))
                .inputs(GAMetaItems.UHPIC.getStackForm(64))
                .input(OrePrefix.wireGtHex, UVSuperconductor, 64)
                .input(OrePrefix.plateDense, Mendelevium.getMaterial(), 4)
                .input(OrePrefix.plateDense, Seaborgium, 4)
                .inputs(MetaItems.FIELD_GENERATOR_UV.getStackForm(16))
                .inputs(MetaItems.EMITTER_UV.getStackForm(16))
                .inputs(MetaItems.SENSOR_UV.getStackForm(16))
                .inputs(GATileEntities.FUSION_REACTOR[2].getStackForm())
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite, 16)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite, 16)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite, 16)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite,16)
                .outputs(INDUSTRIAL_FUSION_REACTOR_UV.getStackForm())
                .EUt(180000)
                .duration(1000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(Helium.getFluid(4000))
                .inputs(MetaItems.NEUTRON_REFLECTOR.getStackForm(8))
                .input(OrePrefix.cableGtQuadruple, UEVSuperconductor, 4)
                .inputs(GAMetaItems.FIELD_GENERATOR_UHV.getStackForm(2))
                .input(OrePrefix.plate, Bohrium, 2)
                .input(OrePrefix.circuit, UEV, 1)
                .outputs(TJMetaBlocks.FUSION_CASING.getItemVariant(BlockFusionCasings.FusionType.FUSION_COIL_UHV))
                .duration(400)
                .EUt(GAValues.VA[9])
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(Helium.getFluid(4000))
                .fluidInputs(Neon.getFluid(4000))
                .fluidInputs(Krypton.getFluid(4000))
                .fluidInputs(Xenon.getFluid(4000))
                .inputs(NEUTRON_REFLECTOR.getStackForm(10))
                .input(OrePrefix.cableGtQuadruple, UMVSuperconductor, 4)
                .inputs(FIELD_GENERATOR_UEV.getStackForm(2))
                .input(OrePrefix.plate, Periodicium, 4)
                .input(OrePrefix.circuit, UIV, 1)
                .outputs(TJMetaBlocks.FUSION_CASING.getItemVariant(BlockFusionCasings.FusionType.FUSION_COIL_UEV))
                .duration(400)
                .EUt(GAValues.VA[10])
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(11520))
                .fluidInputs(Lubricant.getFluid(16000))
                .fluidInputs(SuperheavyLAlloy.getFluid(11520))
                .fluidInputs(SuperheavyHAlloy.getFluid(11520))
                .inputs(GAMetaItems.UHPIC.getStackForm(64))
                .inputs(GAMetaItems.UHPIC.getStackForm(64))
                .input(OrePrefix.wireGtHex, UEVSuperconductor, 64)
                .input(OrePrefix.plateDense, Quantum, 4)
                .input(OrePrefix.plateDense, HastelloyX78, 4)
                .inputs(GAMetaItems.FIELD_GENERATOR_UEV.getStackForm(16))
                .inputs(GAMetaItems.EMITTER_UEV.getStackForm(16))
                .inputs(GAMetaItems.SENSOR_UEV.getStackForm(16))
                .inputs(TJMetaBlocks.FUSION_CASING.getItemVariant(BlockFusionCasings.FusionType.FUSION_COIL_UHV))
                .input(OrePrefix.circuit, UIV, 16)
                .input(OrePrefix.circuit, UIV, 16)
                .input(OrePrefix.circuit, UIV, 16)
                .input(OrePrefix.circuit, UIV,16)
                .outputs(INDUSTRIAL_FUSION_REACTOR_UHV.getStackForm())
                .EUt(1800000)
                .duration(1000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(DenseNeutronPlasma.getFluid(18000))
                .fluidInputs(QCDMatter.getFluid(20736))
                .inputs(EXOTIC_CHIP.getStackForm(64))
                .inputs(EXOTIC_CHIP.getStackForm(64))
                .input(OrePrefix.wireGtHex, UMVSuperconductor, 64)
                .input(OrePrefix.plateDense, Neutronium, 4)
                .input(OrePrefix.plateDense, CosmicNeutronium, 4)
                .inputs(FIELD_GENERATOR_UMV.getStackForm(16))
                .inputs(EMITTER_UMV.getStackForm(16))
                .inputs(SENSOR_UMV.getStackForm(16))
                .inputs(TJMetaBlocks.FUSION_CASING.getItemVariant(BlockFusionCasings.FusionType.FUSION_COIL_UEV))
                .input(OrePrefix.circuit, UXV, 16)
                .input(OrePrefix.circuit, UXV, 16)
                .input(OrePrefix.circuit, UXV, 16)
                .input(OrePrefix.circuit, UXV, 16)
                .outputs(INDUSTRIAL_FUSION_REACTOR_UEV.getStackForm())
                .EUt(180000000)
                .duration(1000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(4608))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Naquadria.getFluid(2304))
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(16))
                .inputs(MetaItems.CONVEYOR_MODULE_UV.getStackForm(16))
                .inputs(MetaItems.ELECTRIC_PISTON_UV.getStackForm(16))
                .inputs(MetaItems.EMITTER_UV.getStackForm(16))
                .inputs(MetaItems.FIELD_GENERATOR_UV.getStackForm(16))
                .inputs(MetaItems.ROBOT_ARM_UV.getStackForm(16))
                .inputs(MetaItems.SENSOR_UV.getStackForm(16))
                .input(OrePrefix.plateDense, Tritanium, 6)
                .input(OrePrefix.ring, Duranium, 64)
                .input(OrePrefix.screw, Dubnium, 32)
                .input(OrePrefix.screw, Tritanium, 32)
                .input(OrePrefix.wireGtDouble, ZPMSuperconductor, 32)
                .input(OrePrefix.wireFine, ThoriumDopedTungsten, 64)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite, 4)
                .outputs(LARGE_WORLD_ACCELERATOR.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(2400)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(4608))
                .fluidInputs(Polyetheretherketone.getFluid(9216))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Naquadria.getFluid(2304))
                .inputs(GATileEntities.FLUID_DRILLING_PLANT[2].getStackForm(16))
                .input(OrePrefix.circuit, UEV, 16)
                .inputs(GAMetaItems.ELECTRIC_MOTOR_UHV.getStackForm(64))
                .inputs(GAMetaItems.ELECTRIC_PUMP_UHV.getStackForm(64))
                .input(OrePrefix.stickLong, NaquadriaticTaranium, 16)
                .input(OrePrefix.gearSmall, TitanSteel, 32)
                .input(OrePrefix.gear, Taranium, 16)
                .input(OrePrefix.plate, Seaborgium, 32)
                .input(OrePrefix.foil, Pikyonium, 64)
                .input(OrePrefix.pipeLarge, EnrichedNaquadahAlloy, 64)
                .input(OrePrefix.screw, Duranium, 48)
                .input(OrePrefix.wireGtSingle, UHVSuperconductor, 64)
                .input(OrePrefix.frameGt, HDCS, 16)
                .outputs(INFINITE_FLUID_DRILL.getStackForm())
                .EUt(GAValues.VA[10])
                .duration(2400)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(Plastic.getFluid(9216))
                .fluidInputs(PolyvinylChloride.getFluid(4608))
                .fluidInputs(Polytetrafluoroethylene.getFluid(2304))
                .fluidInputs(Polybenzimidazole.getFluid(1152))
                .input(OrePrefix.cableGtQuadruple, Platinum, 64)
                .input(OrePrefix.foil, Polycaprolactam, 64)
                .input(OrePrefix.foil, Polystyrene, 64)
                .input(OrePrefix.foil, PolyphenyleneSulfide, 64)
                .input(OrePrefix.foil, Rubber, 64)
                .inputs(ELECTRIC_MOTOR_IV.getStackForm(32))
                .inputs(ELECTRIC_PUMP_IV.getStackForm(32))
                .inputs(GATileEntities.LARGE_CHEMICAL_REACTOR.getStackForm(16))
                .input(OrePrefix.circuit, Master)
                .input(OrePrefix.circuit, Master)
                .input(OrePrefix.circuit, Master)
                .input(OrePrefix.circuit, Master)
                .outputs(PARALLEL_CHEMICAL_REACTOR.getStackForm())
                .EUt(GAValues.VA[6])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Polyetheretherketone.getFluid(18432))
                .inputs(CHEMICAL_PLANT.getStackForm(16))
                .input(OrePrefix.gearSmall, Tritanium, 32)
                .input(OrePrefix.stickLong, LithiumTitanate, 64)
                .input(OrePrefix.pipeLarge, Ultimet, 40)
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(64))
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite,16)
                .inputs(MetaItems.FIELD_GENERATOR_UV.getStackForm(10))
                .input(OrePrefix.wireFine, CarbonNanotubes, 64)
                .input(OrePrefix.foil, HDCS, 64)
                .input(OrePrefix.plateDense, Grisium, 8)
                .inputs(GAMetaBlocks.MUTLIBLOCK_CASING.getItemVariant(GAMultiblockCasing.CasingType.PTFE_PIPE, 64))
                .inputs(GAMetaBlocks.MUTLIBLOCK_CASING.getItemVariant(GAMultiblockCasing.CasingType.CHEMICALLY_INERT, 64))
                .outputs(ADVANCED_PARALLEL_CHEMICAL_REACTOR.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Stellite.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_MACERATOR.getStackForm(16))
                .inputs(MetaItems.COMPONENT_GRINDER_TUNGSTEN.getStackForm(64))
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(32))
                .inputs(MetaItems.ELECTRIC_PISTON_UV.getStackForm(32))
                .input(OrePrefix.gear, TungstenTitaniumCarbide, 16)
                .input(OrePrefix.wireGtQuadruple, NaquadahAlloy, 64)
                .input(OrePrefix.frameGt, Stellite, 16)
                .input(OrePrefix.plateDense, Stellite, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_MACERATOR.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Grisium.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_WASHING_PLANT.getStackForm(16))
                .input(OrePrefix.pipeLarge, TungstenSteel, 64)
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(32))
                .inputs(ELECTRIC_PUMP_UV.getStackForm(32))
                .input(OrePrefix.gear, Talonite, 16)
                .input(OrePrefix.cableGtQuadruple, Duranium, 64)
                .input(OrePrefix.frameGt, Grisium, 16)
                .input(OrePrefix.plateDense, Grisium, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_WASHING_MACHINE.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(RedSteel.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_CENTRIFUGE.getStackForm(16))
                .input(OrePrefix.pipeLarge, TungstenSteel, 64)
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(32))
                .inputs(ELECTRIC_PUMP_UV.getStackForm(32))
                .input(OrePrefix.gear, Titanium, 16)
                .input(OrePrefix.cableGtQuadruple, Duranium, 64)
                .input(OrePrefix.frameGt, RedSteel, 16)
                .input(OrePrefix.plateDense, RedSteel, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_CENTRIFUGE.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Potin.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_ELECTROLYZER.getStackForm(16))
                .inputs(MetaItems.LARGE_FLUID_CELL_TUNGSTEN_STEEL.getStackForm(16))
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(32))
                .inputs(ELECTRIC_PUMP_UV.getStackForm(32))
                .input(OrePrefix.gear, Osmiridium, 16)
                .input(OrePrefix.cableGtQuadruple, Duranium, 64)
                .input(OrePrefix.frameGt, Potin, 16)
                .input(OrePrefix.plateDense, Potin, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_ELECTROLYZER.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(EglinSteel.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_SIFTER.getStackForm(16))
                .inputs(MetaItems.ITEM_FILTER.getStackForm(64))
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(32))
                .inputs(MetaItems.ELECTRIC_PISTON_UV.getStackForm(32))
                .input(OrePrefix.gear, RoseGold, 16)
                .input(OrePrefix.cableGtQuadruple, NaquadahAlloy, 64)
                .input(OrePrefix.frameGt, EglinSteel, 16)
                .input(OrePrefix.plateDense, EglinSteel, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_SIFTER.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Grisium.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_BREWERY.getStackForm(16))
                .input(OrePrefix.pipeLarge, Zeron100, 64)
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(32))
                .inputs(ELECTRIC_PUMP_UV.getStackForm(32))
                .input(OrePrefix.gear, Ultimet, 16)
                .input(OrePrefix.cableGtQuadruple, Duranium, 64)
                .input(OrePrefix.frameGt, Grisium, 16)
                .input(OrePrefix.plateDense, Grisium, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_BREWERY.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Invar.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_ARC_FURNACE.getStackForm(16))
                .input(OrePrefix.pipeLarge, TantalumHafniumSeaborgiumCarbide, 64)
                .inputs(ELECTRIC_MOTOR_UHV.getStackForm(32))
                .inputs(ELECTRIC_PUMP_UHV.getStackForm(32))
                .input(OrePrefix.gear, Titanium, 16)
                .input(OrePrefix.cableGtQuadruple, AbyssalAlloy, 64)
                .input(OrePrefix.frameGt, Invar, 16)
                .input(OrePrefix.plateDense, Invar, 8)
                .input(OrePrefix.circuit, UEV)
                .input(OrePrefix.circuit, UEV)
                .input(OrePrefix.circuit, UEV)
                .input(OrePrefix.circuit, UEV)
                .outputs(PARALLEL_LARGE_ARC_FURNACE.getStackForm())
                .EUt(GAValues.VA[10])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(HastelloyN.getFluid(18432))
                .fluidInputs(Zylon.getFluid(9216))
                .inputs(LARGE_ASSEMBLER.getStackForm(16))
                .inputs(CONVEYOR_MODULE_UEV.getStackForm(32))
                .inputs(ROBOT_ARM_UEV.getStackForm(32))
                .inputs(SENSOR_UEV.getStackForm(16))
                .inputs(EMITTER_UEV.getStackForm(16))
                .input(OrePrefix.gear, Staballoy, 16)
                .input(OrePrefix.cableGtQuadruple, TitanSteel, 64)
                .input(OrePrefix.frameGt, HastelloyN, 16)
                .input(OrePrefix.plateDense, HastelloyN, 8)
                .input(OrePrefix.circuit, UIV)
                .input(OrePrefix.circuit, UIV)
                .input(OrePrefix.circuit, UIV)
                .input(OrePrefix.circuit, UIV)
                .outputs(PARALLEL_LARGE_ASSEMBLER.getStackForm())
                .EUt(GAValues.VA[11])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Titanium.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_BENDER_AND_FORMING.getStackForm(16))
                .inputs(new ItemStack(Blocks.ANVIL, 64))
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(32))
                .inputs(ELECTRIC_PISTON_UV.getStackForm(32))
                .input(OrePrefix.gear, Titanium, 16)
                .input(OrePrefix.cableGtQuadruple, NaquadahAlloy, 64)
                .input(OrePrefix.frameGt, Titanium, 16)
                .input(OrePrefix.plateDense, Titanium, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_BENDING_AND_FORMING.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Steel.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_CANNING_MACHINE.getStackForm(16))
                .inputs(new ItemStack(Items.GLASS_BOTTLE, 64))
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(32))
                .inputs(ELECTRIC_PUMP_UV.getStackForm(32))
                .input(OrePrefix.gear, Steel, 16)
                .input(OrePrefix.cableGtQuadruple, Duranium, 64)
                .input(OrePrefix.frameGt, Steel, 16)
                .input(OrePrefix.plateDense, Steel, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_CANNING_MACHINE.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(MaragingSteel250.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_CUTTING.getStackForm(16))
                .inputs(COMPONENT_GRINDER_TUNGSTEN.getStackForm(64))
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(32))
                .inputs(CONVEYOR_MODULE_UV.getStackForm(32))
                .input(OrePrefix.gear, MaragingSteel250, 16)
                .input(OrePrefix.cableGtQuadruple, Duranium, 64)
                .input(OrePrefix.frameGt, MaragingSteel250, 16)
                .input(OrePrefix.plateDense, MaragingSteel250, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_CUTTING_MACHINE.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(BabbittAlloy.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_ELECTROMAGNET.getStackForm(16))
                .input(OrePrefix.gemExquisite, MagnetoResonatic, 16)
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(32))
                .inputs(CONVEYOR_MODULE_UV.getStackForm(32))
                .input(OrePrefix.stickLong, VanadiumGallium, 16)
                .input(OrePrefix.wireGtOctal, Graphene, 64)
                .input(OrePrefix.frameGt, BabbittAlloy, 16)
                .input(OrePrefix.plateDense, BabbittAlloy, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_ELECTROMAGNET.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Talonite.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_EXTRACTOR.getStackForm(16))
                .input(OrePrefix.pipeLarge, TungstenSteel, 64)
                .inputs(ELECTRIC_PISTON_UV.getStackForm(32))
                .inputs(ELECTRIC_PUMP_UV.getStackForm(32))
                .input(OrePrefix.gear, Talonite, 16)
                .input(OrePrefix.cableGtQuadruple, Duranium, 64)
                .input(OrePrefix.frameGt, Talonite, 16)
                .input(OrePrefix.plateDense, Talonite, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_EXTRACTOR.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Inconel625.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_EXTRUDER.getStackForm(16))
                .inputs(SHAPE_EMPTY.getStackForm(64))
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(32))
                .inputs(ELECTRIC_PISTON_UV.getStackForm(32))
                .input(OrePrefix.gear, Inconel625, 16)
                .input(OrePrefix.cableGtQuadruple, NaquadahAlloy, 64)
                .input(OrePrefix.frameGt, Inconel625, 16)
                .input(OrePrefix.plateDense, Inconel625, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_EXTRUDER.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Iron.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_FORGE_HAMMER.getStackForm(16))
                .inputs(new ItemStack(Blocks.ANVIL, 64))
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(32))
                .inputs(ELECTRIC_PISTON_UV.getStackForm(32))
                .input(OrePrefix.gear, Iron, 16)
                .input(OrePrefix.cableGtQuadruple, NaquadahAlloy, 64)
                .input(OrePrefix.frameGt, Iron, 16)
                .input(OrePrefix.plateDense, Iron, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_FORGE_HAMMER.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(HG1223.getFluid(18432))
                .fluidInputs(Zylon.getFluid(9216))
                .inputs(LARGE_LASER_ENGRAVER.getStackForm(16))
                .inputs(CONVEYOR_MODULE_UEV.getStackForm(32))
                .inputs(ROBOT_ARM_UEV.getStackForm(32))
                .inputs(SENSOR_UEV.getStackForm(32))
                .inputs(EMITTER_UEV.getStackForm(32))
                .input(OrePrefix.gear, HSSG, 16)
                .input(OrePrefix.gear, RhodiumPlatedPalladium, 16)
                .input(OrePrefix.cableGtQuadruple, TitanSteel, 64)
                .input(OrePrefix.frameGt, Zeron100, 16)
                .input(OrePrefix.plateDense, HSSG, 8)
                .input(OrePrefix.circuit, UIV)
                .input(OrePrefix.circuit, UIV)
                .input(OrePrefix.circuit, UIV)
                .input(OrePrefix.circuit, UIV)
                .outputs(PARALLEL_LARGE_LASER_ENGRAVER.getStackForm())
                .EUt(GAValues.VA[11])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Staballoy.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_MIXER.getStackForm(16))
                .input(OrePrefix.rotor, Taranium, 64)
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(32))
                .inputs(ELECTRIC_PUMP_UV.getStackForm(32))
                .input(OrePrefix.gear, TungstenCarbide, 16)
                .input(OrePrefix.cableGtQuadruple, Duranium, 64)
                .input(OrePrefix.frameGt, Staballoy, 16)
                .input(OrePrefix.plateDense, Staballoy, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_MIXER.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(HG1223.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_PACKAGER.getStackForm(16))
                .inputs(SCHEMATIC.getStackForm(64))
                .inputs(CONVEYOR_MODULE_UV.getStackForm(32))
                .inputs(ROBOT_ARM_UV.getStackForm(32))
                .input(OrePrefix.gear, HG1223, 16)
                .input(OrePrefix.cableGtQuadruple, NaquadahAlloy, 64)
                .input(OrePrefix.frameGt, HG1223, 16)
                .input(OrePrefix.plateDense, HG1223, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_PACKAGER.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(MaragingSteel250.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(LARGE_WIREMILL.getStackForm(16))
                .inputs(SCHEMATIC.getStackForm(64))
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(32))
                .inputs(ELECTRIC_PISTON_UV.getStackForm(32))
                .input(OrePrefix.gear, MaragingSteel250, 16)
                .input(OrePrefix.cableGtQuadruple, NaquadahAlloy, 64)
                .input(OrePrefix.frameGt, MaragingSteel250, 16)
                .input(OrePrefix.plateDense, MaragingSteel250, 8)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .input(OrePrefix.circuit, MarkerMaterials.Tier.Infinite)
                .outputs(PARALLEL_LARGE_WIREMILL.getStackForm())
                .EUt(GAValues.VA[9])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(HastelloyN.getFluid(18432))
                .fluidInputs(Zylon.getFluid(9216))
                .inputs(PLASMA_CONDENSER.getStackForm(16))
                .inputs(ELECTRIC_MOTOR_UEV.getStackForm(32))
                .inputs(ELECTRIC_PUMP_UEV.getStackForm(32))
                .inputs(SENSOR_UEV.getStackForm(16))
                .input(OrePrefix.gear, TungstenCarbide, 16)
                .input(OrePrefix.gear, RhodiumPlatedPalladium, 16)
                .input(OrePrefix.cableGtQuadruple, TitanSteel, 64)
                .input(OrePrefix.frameGt, HastelloyN, 16)
                .input(OrePrefix.plateDense, HastelloyN, 8)
                .input(OrePrefix.circuit, UIV)
                .input(OrePrefix.circuit, UIV)
                .input(OrePrefix.circuit, UIV)
                .input(OrePrefix.circuit, UIV)
                .outputs(PARALLEL_PLASMA_CONDENSER.getStackForm())
                .EUt(GAValues.VA[11])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(ZirconiumCarbide.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(ALLOY_BLAST_FURNACE.getStackForm(16))
                .inputs(ELECTRIC_MOTOR_LUV.getStackForm(32))
                .inputs(ELECTRIC_PISTON_LUV.getStackForm(32))
                .input(OrePrefix.gear, TungstenCarbide, 16)
                .input(OrePrefix.cableGtQuadruple, YttriumBariumCuprate, 64)
                .input(OrePrefix.frameGt, Staballoy, 16)
                .input(OrePrefix.plateDense, ZirconiumCarbide, 8)
                .input(OrePrefix.circuit, Ultimate)
                .input(OrePrefix.circuit, Ultimate)
                .input(OrePrefix.circuit, Ultimate)
                .input(OrePrefix.circuit, Ultimate)
                .outputs(PARALLEL_ALLOY_BLAST_FURNACE.getStackForm())
                .EUt(GAValues.VA[7])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Invar.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(ELECTRIC_BLAST_FURNACE.getStackForm(16))
                .inputs(ELECTRIC_MOTOR_IV.getStackForm(32))
                .inputs(ELECTRIC_PISTON_IV.getStackForm(32))
                .input(OrePrefix.gear, Invar, 16)
                .input(OrePrefix.cableGtQuadruple, Osmium, 64)
                .input(OrePrefix.frameGt, Invar, 16)
                .input(OrePrefix.plateDense, Invar, 8)
                .input(OrePrefix.circuit, Master)
                .input(OrePrefix.circuit, Master)
                .input(OrePrefix.circuit, Master)
                .input(OrePrefix.circuit, Master)
                .outputs(PARALLEL_ELECTRIC_BLAST_FURNACE.getStackForm())
                .EUt(GAValues.VA[6])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(Aluminium.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(VACUUM_FREEZER.getStackForm(16))
                .inputs(ELECTRIC_MOTOR_IV.getStackForm(32))
                .inputs(ELECTRIC_PUMP_IV.getStackForm(32))
                .input(OrePrefix.gear, StainlessSteel, 16)
                .input(OrePrefix.cableGtQuadruple, Osmium, 64)
                .input(OrePrefix.frameGt, Aluminium, 16)
                .input(OrePrefix.plateDense, Aluminium, 8)
                .input(OrePrefix.circuit, Master)
                .input(OrePrefix.circuit, Master)
                .input(OrePrefix.circuit, Master)
                .input(OrePrefix.circuit, Master)
                .outputs(PARALLEL_VACUUM_FREEZER.getStackForm())
                .EUt(GAValues.VA[6])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(IncoloyMA956.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(CRYOGENIC_FREEZER.getStackForm(16))
                .inputs(ELECTRIC_MOTOR_ZPM.getStackForm(32))
                .inputs(ELECTRIC_PUMP_ZPM.getStackForm(32))
                .inputs(ELECTRIC_PISTON_ZPM.getStackForm(32))
                .input(OrePrefix.gear, IncoloyMA956, 16)
                .input(OrePrefix.cableGtQuadruple, Naquadah, 64)
                .input(OrePrefix.frameGt, IncoloyMA956, 16)
                .input(OrePrefix.plateDense, HG1223, 8)
                .input(OrePrefix.circuit, Superconductor)
                .input(OrePrefix.circuit, Superconductor)
                .input(OrePrefix.circuit, Superconductor)
                .input(OrePrefix.circuit, Superconductor)
                .outputs(PARALLEL_CRYOGENIC_FREEZER.getStackForm())
                .EUt(GAValues.VA[8])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(18432))
                .fluidInputs(Lubricant.getFluid(64000))
                .fluidInputs(HastelloyN.getFluid(18432))
                .fluidInputs(Polybenzimidazole.getFluid(9216))
                .inputs(VOLCANUS.getStackForm(16))
                .inputs(ELECTRIC_MOTOR_ZPM.getStackForm(32))
                .inputs(ELECTRIC_PUMP_ZPM.getStackForm(32))
                .inputs(ROBOT_ARM_ZPM.getStackForm(32))
                .input(OrePrefix.gear, HastelloyN, 16)
                .input(OrePrefix.cableGtQuadruple, Naquadah, 64)
                .input(OrePrefix.frameGt, HastelloyN, 16)
                .input(OrePrefix.plateDense, HastelloyN, 8)
                .input(OrePrefix.circuit, Superconductor)
                .input(OrePrefix.circuit, Superconductor)
                .input(OrePrefix.circuit, Superconductor)
                .input(OrePrefix.circuit, Superconductor)
                .outputs(PARALLEL_VOLCANUS.getStackForm())
                .EUt(GAValues.VA[8])
                .duration(3000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(9216))
                .fluidInputs(Lubricant.getFluid(16000))
                .fluidInputs(Polybenzimidazole.getFluid(4608))
                .inputs(new ItemStack(Item.getByNameOrId("fluxnetworks:fluxcontroller")))
                .inputs(new ItemStack(Item.getByNameOrId("fluxnetworks:fluxcore"), 64))
                .inputs(new ItemStack(Item.getByNameOrId("fluxnetworks:fluxblock"), 16))
                .input(OrePrefix.plateDense, Talonite, 4)
                .inputs(MetaItems.EMITTER_IV.getStackForm(16))
                .inputs(MetaItems.EMITTER_LUV.getStackForm(16))
                .inputs(MetaItems.EMITTER_ZPM.getStackForm(16))
                .inputs(MetaItems.EMITTER_UV.getStackForm(16))
                .input(OrePrefix.circuit, Infinite, 4)
                .input(OrePrefix.wireGtQuadruple, UVSuperconductor, 64)
                .input(OrePrefix.wireGtQuadruple, UVSuperconductor, 64)
                .input(OrePrefix.wireGtQuadruple, UVSuperconductor, 64)
                .outputs(LARGE_WIRELESS_ENERGY_EMITTER.getStackForm())
                .EUt(GAValues.VA[8])
                .duration(2000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(9216))
                .fluidInputs(Lubricant.getFluid(16000))
                .fluidInputs(Polybenzimidazole.getFluid(4608))
                .inputs(new ItemStack(Item.getByNameOrId("fluxnetworks:fluxcontroller")))
                .inputs(new ItemStack(Item.getByNameOrId("fluxnetworks:fluxcore"), 64))
                .inputs(new ItemStack(Item.getByNameOrId("fluxnetworks:fluxblock"), 16))
                .input(OrePrefix.plateDense, Talonite, 4)
                .inputs(MetaItems.SENSOR_IV.getStackForm(16))
                .inputs(MetaItems.SENSOR_LUV.getStackForm(16))
                .inputs(MetaItems.SENSOR_ZPM.getStackForm(16))
                .inputs(MetaItems.SENSOR_UV.getStackForm(16))
                .input(OrePrefix.circuit, Infinite, 4)
                .input(OrePrefix.wireGtQuadruple, UVSuperconductor, 64)
                .input(OrePrefix.wireGtQuadruple, UVSuperconductor, 64)
                .input(OrePrefix.wireGtQuadruple, UVSuperconductor, 64)
                .outputs(LARGE_WIRELESS_ENERGY_RECEIVER.getStackForm())
                .EUt(GAValues.VA[8])
                .duration(2000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(9216))
                .fluidInputs(Lubricant.getFluid(16000))
                .fluidInputs(Polybenzimidazole.getFluid(4608))
                .inputs(new ItemStack(Item.getByNameOrId("fluxnetworks:fluxcontroller")))
                .inputs(new ItemStack(Item.getByNameOrId("fluxnetworks:fluxcore"), 64))
                .inputs(new ItemStack(Item.getByNameOrId("fluxnetworks:fluxblock"), 16))
                .input(OrePrefix.plateDense, Talonite, 4)
                .inputs(GAMetaBlocks.CELL_CASING.getItemVariant(CellCasing.CellType.CELL_HV, 16))
                .inputs(GAMetaBlocks.CELL_CASING.getItemVariant(CellCasing.CellType.CELL_EV, 16))
                .inputs(GAMetaBlocks.CELL_CASING.getItemVariant(CellCasing.CellType.CELL_IV, 16))
                .inputs(GAMetaBlocks.CELL_CASING.getItemVariant(CellCasing.CellType.CELL_LUV, 16))
                .inputs(GAMetaBlocks.CELL_CASING.getItemVariant(CellCasing.CellType.CELL_ZPM, 16))
                .inputs(GAMetaBlocks.CELL_CASING.getItemVariant(CellCasing.CellType.CELL_UV, 16))
                .input(OrePrefix.circuit, Infinite, 4)
                .input(OrePrefix.wireGtQuadruple, UVSuperconductor, 64)
                .outputs(LARGE_BATTERY_CHARGER.getStackForm())
                .EUt(GAValues.VA[8])
                .duration(2000)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(7776))
                .fluidInputs(FullerenePolymerMatrix.getFluid(2592))
                .input(OrePrefix.cableGtSingle, UMVSuperconductor, 64)
                .input(OrePrefix.cableGtSingle, UMVSuperconductor, 64)
                .input(OrePrefix.cableGtSingle, UMVSuperconductor, 64)
                .input(OrePrefix.cableGtSingle, UMVSuperconductor, 64)
                .input(OrePrefix.screw, HeavyQuarkDegenerateMatter, 64)
                .input(OrePrefix.screw, Periodicium, 64)
                .input(OrePrefix.stick, Taranium, 16)
                .inputs(ELECTRIC_MOTOR_UMV.getStackForm(8))
                .input(OrePrefix.plate, CosmicNeutronium, 8)
                .input(OrePrefix.circuit, UMV, 4)
                .input(OrePrefix.gear, QCDMatter, 4)
                .inputs(SENSOR_UMV.getStackForm(2))
                .inputs(VOID_MINER[2].getStackForm())
                .outputs(VOID_MORE_MINER.getStackForm())
                .EUt(64000000)
                .duration(600)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(4608))
                .fluidInputs(EnderPearl.getFluid(10000))
                .fluidInputs(EnderEye.getFluid(10000))
                .inputs(HULL[7].getStackForm())
                .inputs(new ItemStack(Item.getByNameOrId("enderio:item_material"), 1, 44))
                .inputs(new ItemStack(Item.getByNameOrId("enderio:item_material"), 1, 42))
                .inputs(new ItemStack(Item.getByNameOrId("draconicevolution:dislocator_advanced")))
                .inputs(FIELD_GENERATOR_ZPM.getStackForm(2))
                .inputs(EMITTER_ZPM.getStackForm(2))
                .inputs(SENSOR_ZPM.getStackForm(2))
                .input(OrePrefix.circuit, Superconductor, 4)
                .input(OrePrefix.wireGtSingle, Naquadah, 16)
                .input(OrePrefix.screw, Enderium, 64)
                .outputs(TELEPORTER.getStackForm())
                .EUt(GAValues.VA[7])
                .duration(600)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(4608))
                .fluidInputs(FluidRegistry.getFluidStack("xpjuice", 61440))
                .fluidInputs(Lubricant.getFluid(16000))
                .inputs(HULL[8].getStackForm())
                .input(OrePrefix.plate, Diamond, 50)
                .input(OrePrefix.plate, Lapis, 60)
                .input(OrePrefix.circuit, Infinite, 10)
                .input(OrePrefix.screw, Tritanium, 64)
                .input(OrePrefix.gear, Dubnium, 10)
                .input(OrePrefix.cableGtSingle, NaquadahAlloy, 16)
                .inputs(ELECTRIC_PUMP_UV.getStackForm(8))
                .inputs(ELECTRIC_MOTOR_UV.getStackForm(4))
                .inputs(EMITTER_UV.getStackForm(4))
                .outputs(LARGE_ENCHANTER.getStackForm())
                .EUt(GAValues.VA[8])
                .duration(600)
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(4608))
                .fluidInputs(Lubricant.getFluid(16000))
                .input(OrePrefix.screw, Naquadah, 64)
                .input(OrePrefix.screw, HSSS, 64)
                .input(OrePrefix.plate, RhodiumPlatedPalladium, 48)
                .input(OrePrefix.plate, Staballoy, 48)
                .input(OrePrefix.circuit, Ultimate, 24)
                .input(OrePrefix.gear, Inconel625, 16)
                .input(OrePrefix.gear, HastelloyN, 16)
                .inputs(new ItemStack(Item.getByNameOrId("appliedenergistics2:molecular_assembler"), 16))
                .inputs(new ItemStack(Item.getByNameOrId("enderio:block_crafter"), 16))
                .inputs(ELECTRIC_PISTON_LUV.getStackForm(8))
                .inputs(CONVEYOR_MODULE_LUV.getStackForm(8))
                .inputs(ROBOT_ARM_LUV.getStackForm(8))
                .inputs(SENSOR_LUV.getStackForm(8))
                .inputs(EMITTER_LUV.getStackForm(8))
                .outputs(LARGE_CRAFTER.getStackForm())
                .EUt(GAValues.VA[6])
                .duration(2000)
                .buildAndRegister();

        List<ItemStack> turbineUpgrade = new ArrayList<>();
        for (int i = 0; i < TURBINE_UPGRADES.length; i++) {
            if (i > 0)
                turbineUpgrade.set(0, TURBINE_UPGRADES[i - 1].getStackForm());
            else turbineUpgrade.add(new ItemStack(Item.getByNameOrId("ironbackpacks:upgrade")));
            ASSEMBLY_LINE_RECIPES.recipeBuilder()
                    .fluidInputs(SolderingAlloy.getFluid(9216))
                    .fluidInputs(Lubricant.getFluid(64000))
                    .input(OrePrefix.gear, MATERIAL_TIER[0][i + GAValues.UV], 4)
                    .input(OrePrefix.plateDense, MATERIAL_TIER[0][i + GAValues.UV], 7)
                    .input(OrePrefix.screw, MATERIAL_TIER[0][i + GAValues.UV], 64)
                    .inputs(turbineUpgrade)
                    .inputs(UHPIC.getStackForm(64))
                    .inputs(motors[i + GAValues.UV].getStackForm(4))
                    .inputs(pumps[i + GAValues.UV].getStackForm(4))
                    .inputs(robotArms[i + GAValues.UV].getStackForm(4))
                    .outputs(TURBINE_UPGRADES[i].getStackForm())
                    .EUt(GAValues.VA[i + GAValues.UHV])
                    .duration(1500)
                    .buildAndRegister();
        }
        ItemStack sodiumPotassiumCell = LARGE_FLUID_CELL_STEEL.getStackForm(), sodiumPotassiumCell2 = LARGE_FLUID_CELL_TUNGSTEN_STEEL.getStackForm();
        NBTTagCompound cellCompound = new NBTTagCompound(), cellCompound2 = new NBTTagCompound(), fluidCompound = new NBTTagCompound(), fluidCompound2 = new NBTTagCompound();
        fluidCompound.setString("FluidName", "sodium_potassium_alloy");
        fluidCompound.setInteger("Amount", 64000);
        cellCompound.setTag("Fluid", fluidCompound);
        sodiumPotassiumCell.setTagCompound(cellCompound);
        fluidCompound2.setString("FluidName", "sodium_potassium_alloy");
        fluidCompound2.setInteger("Amount", 256000);
        cellCompound2.setTag("Fluid", fluidCompound2);
        sodiumPotassiumCell2.setTagCompound(cellCompound2);

        for (int i = 0, count = 1; i < ENDER_ENERGY_INPUT_HATCHES.length; i++, count++) {
            ItemStack stack = i > 7 ? sodiumPotassiumCell2 : sodiumPotassiumCell;
            stack.setCount(count - (i > 7 ? 7 : 0));
            ASSEMBLY_LINE_RECIPES.recipeBuilder()
                    .fluidInputs(SolderingAlloy.getFluid(4608), Lubricant.getFluid(16000), EnderPearl.getFluid(1440), EnderEye.getFluid(1440))
                    .inputs(stack, UHPIC.getStackForm(16), RecipeInit.getEnergyHatch(i + 1, false), ENDER_ENERGY_COVERS[Math.max(0, i - 2)].getStackForm(), EMITTER_UHV.getStackForm(), SENSOR_UHV.getStackForm())
                    .input(OrePrefix.circuit, UEV, 2)
                    .outputs(ENDER_ENERGY_INPUT_HATCHES[i].getStackForm())
                    .duration(1000).EUt(Math.max(GAValues.VA[9], GAValues.VA[i + 1]))
                    .buildAndRegister();

            ASSEMBLY_LINE_RECIPES.recipeBuilder()
                    .fluidInputs(SolderingAlloy.getFluid(4608), Lubricant.getFluid(16000), EnderPearl.getFluid(1440), EnderEye.getFluid(1440))
                    .inputs(stack, UHPIC.getStackForm(16), RecipeInit.getEnergyHatch(i + 1, true), ENDER_ENERGY_COVERS[Math.max(0, i - 2)].getStackForm(), EMITTER_UHV.getStackForm(), SENSOR_UHV.getStackForm())
                    .input(OrePrefix.circuit, UEV, 2)
                    .outputs(ENDER_ENERGY_OUTPUT_HATCHES[i].getStackForm())
                    .duration(1000).EUt(Math.max(GAValues.VA[9], GAValues.VA[i + 1]))
                    .buildAndRegister();
        }

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(57600), Lubricant.getFluid(64000), Bohrium.getFluid(57600), Adamantium.getFluid(57600))
                .inputs(ADVANCED_FUSION_REACTOR.getStackForm(64), ADVANCED_FUSION_REACTOR.getStackForm(64), ADVANCED_FUSION_REACTOR.getStackForm(64), ADVANCED_FUSION_REACTOR.getStackForm(64), UHPIC_WAFER.getStackForm(64), UHPIC_WAFER.getStackForm(64), FIELD_GENERATOR_UHV.getStackForm(64), EMITTER_UHV.getStackForm(64), SENSOR_UHV.getStackForm(64))
                .input(OrePrefix.circuit, UEV, 64)
                .input(OrePrefix.wireGtHex, UHVSuperconductor, 64)
                .input(OrePrefix.gear, Bohrium, 16)
                .input(OrePrefix.gear, Adamantium, 16)
                .input(OrePrefix.plateDense, Mendelevium.getMaterial(), 7)
                .outputs(MEGA_FUSION.getStackForm())
                .duration(2000).EUt(GAValues.VA[10])
                .buildAndRegister();

        ASSEMBLY_LINE_RECIPES.recipeBuilder()
                .fluidInputs(SolderingAlloy.getFluid(14400), Lubricant.getFluid(16000), EnderPearl.getFluid(57600), EnderPearl.getFluid(57600))
                .inputs(BATTERY_TOWER.getStackForm(16), SENSOR_UHV.getStackForm(16), EMITTER_UHV.getStackForm(16), FIELD_GENERATOR_UHV.getStackForm(16))
                .inputs(UHPIC.getStackForm(16))
                .input(OrePrefix.circuit, UEV, 16)
                .input(OrePrefix.circuit, UEV, 16)
                .inputs(UHPIC.getStackForm(16), GAMetaBlocks.METAL_CASING_1.getItemVariant(MetalCasing1.CasingType.TALONITE, 16), UHPIC.getStackForm(16), UHPIC.getStackForm(16), GAMetaBlocks.METAL_CASING_1.getItemVariant(MetalCasing1.CasingType.TALONITE, 16))
                .outputs(ENDER_BATTERY_TOWER.getStackForm())
                .duration(2000).EUt(GAValues.VA[10])
                .buildAndRegister();
    }
}
